name: CI/CD Pipeline - Dev

on:
  push:
    branches:
      - dev

env:
  AWS_ACCOUNT: "357834747308"
  AWS_REGION: "us-east-1"
  APP_NAME: "linuxtips-app"
  CLUSTER_NAME: "linuxtips-ecs-cluster"
  REPOSITORY_NAME: "linuxtips/$APP_NAME"

jobs:
  ci-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      - name: Install GoLint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0

      - name: Lint App
        run: golangci-lint run ./... -E errcheck
        working-directory: ./app

      - name: Test App
        run: go test -v ./...
        working-directory: ./app